### ISSUE TITLE
Cannot redeclare wp_mail(), WordPress 4.8.2

### ISSUE THREAD

**Issue by ViktorPontinen** [mailgun/wordpress-plugin#64] opened 2017-10-16 07:46 UTC
Mailgun Plugin: 1.5.8.5
WordPress: 4.8.2

Error:
`PHP message: PHP Fatal error:  Cannot redeclare wp_mail() (previously declared in .../wp-includes/pluggable.php:173) in .../plugins/mailgun/includes/wp-mail-api.php on line 414"`

Might submit a PR, if time is found.

**Comment by ViktorPontinen** [comment] 2017-10-16 08:02
Also not sure why it's failing. wp_mail() should be overrideable.

**Comment by pirogoeth** [comment] 2017-11-22 21:05
@ViktorPontinen what version of PHP are you using?

**Comment by robbiet480** [comment] 2017-11-23 00:24
Also experiencing this on 4.8.3. Using PHP7 via FPM.

**Comment by pirogoeth** [comment] 2017-11-23 07:04
That's very interesting. I'm running a similar setup (WP 4.9, PHP 7.1) and I'm not seeing any errors like that.

**Comment by ViktorPontinen** [comment] 2017-11-23 08:56
@pirogoeth 
php -v
`7.0.24-1+ubuntu16.04.1+deb.sury.org+1`

**Comment by arunbasillal** [comment] 2017-11-24 09:19
At the time of plugin activation or use, the WordPress pluggable function wp_mail already exists. Checking if function_exists lets the plugin safely activate/initialize. On next WordPress init, pluggable functions are loaded after plugins, so the overriding function in wp-mail-api.php will be used. 

Here is a supporting stackoverflow answer: https://wordpress.stackexchange.com/a/56576/90061

**Comment by pirogoeth** [comment] 2017-11-24 17:22
@ViktorPontinen @robbiet480 could one of y'all test @arunbasillal's PR above (#67)? You should be able to install the [zipball](https://github.com/arunbasillal/mailgun-wordpress-plugin/archive/master.zip) of his PR over the current version of the Mailgun plugin. I would test it, but I was not able to reproduce.

**Comment by kolosovski** [comment] 2017-12-02 21:54
I have the similar issue. Just installed the mailgun plugin, configured and try to test...

PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
WordPress 4.9.1

nginx error.log:
`
2017/12/02 21:42:26 [error] 25893#25893: *284 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare wp_mail() (previously declared in .../wp-includes/pluggable.php:173) in .../wp-content/plugins/mailgun/includes/wp-mail-api.php on line 111" while reading response header from upstream, client: 62.2.1.101, server: example.com, request: "GET /wp-admin/admin-ajax.php?action=mailgun-test&_wpnonce=951954d088 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "example.com", referrer: "http://example.com/wp-admin/options-general.php?page=mailgun"
`

**Comment by arunbasillal** [comment] 2017-12-02 22:01
@kolosovski Can you try using this version and see how it turns out? https://github.com/arunbasillal/mailgun-wordpress-plugin/archive/master.zip

**Comment by kolosovski** [comment] 2017-12-03 10:00
@arunbasillal something has changed this time. No errors, but no positive results either.

error.log (empty)
access.log:
`62.2.1.101 - - [03/Dec/2017:09:54:31 +0000] "POST /wp-admin/admin-ajax.php HTTP/1.1" 200 58 "http://example.com/wp-admin/options-general.php?page=mailgun" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
62.2.1.101 - - [03/Dec/2017:09:54:59 +0000] "GET /wp-admin/admin-ajax.php?action=mailgun-test&_wpnonce=951954d088 HTTP/1.1" 200 65 "http://example.com/wp-admin/options-general.php?page=mailgun" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
`

In chrome dev tools:
request:
http://example.com/wp-admin/admin-ajax.php?action=mailgun-test&_wpnonce=951954d088

response:
`{"message":"Failure","method":"HTTP API","error":null}`

**Comment by jevonearth** [comment] 2018-05-03 18:28
I tested the https://github.com/arunbasillal/mailgun-wordpress-plugin/archive/master.zip and I also get the `{"message":"Failure","method":"HTTP API","error":null}` error.

I'm going to have to switch away from mailgun because of this. 😢 I'll probably be back when it is fixed.

**Comment by dan-at-unkubed** [comment] 2018-09-07 18:29
Got this same error on one of my sites and found this thread. Had other sites on the same server not giving me the issue. Using PHP Version 5.6.37-0+deb8u1

Ended up being a conflict with a plugin called "Find and Replace", but the plugin doesn't have any references to wp_mail(), so I don't know what's causing it. We weren't using the plugin anymore, so I've removed it from the site and am no longer having any issues.

I can't find a current site for the plugin, but the plugin is REALLY small (3 short php files).  So, I've zipped it up and attached it, if someone wants to look through it and try to figure out what is going on.

[find-replace.zip](https://github.com/mailgun/wordpress-plugin/files/2362100/find-replace.zip)

Luck.

**Comment by markbiek** [comment] 2020-09-29 15:27
Running into this on a WordPress 5.4.2 (PHP 7.3) site. I tried disabling all other plugins and it was still an issue

**Comment by markbiek** [comment] 2020-09-30 13:50
It _does_ seem like switching the plugin from using the API to using SMTP still works. In that case, it doesn't try to override `wp_mail`.

**Comment by uavn** [comment] 2020-11-06 19:02
should be fixed now

**Closed by uavn** 2020-11-06 19:02 UTC
